///
/// \brief header file containing configuration values set during cmake build.
///
/// do not edit! this file is generated by cmake during the build process and any changes will be overwritten.
///

#pragma once

/// \brief A string containing the human readable form of the library's current version
#define AUDIOSTREAMS_VERSION "@PROJECT_VERSION@"
#define AUDIOSTREAMS_MAJOR_VERSION @PROJECT_VERSION_MAJOR@
#define AUDIOSTREAMS_MINOR_VERSION @PROJECT_VERSION_MINOR@
#define AUDIOSTREAMS_PATCH_VERSION @PROJECT_VERSION_PATCH@
/// \brief A macro to convert the usual major, minor, patch components of a version to a single unsigned 32bit integer.
#define MAKE_NUMERIC_VERSION(x, y, z) (((x)&0xff)<<24+((y)&0xff)<<16+((z)&0xffff))
#define AUDIOSTREAMS_NUMERIC_VERSION MAKE_NUMERIC_VERSION(AUDIOSTREAMS_MAJOR_VERSION, AUDIOSTREAMS_MINOR_VERSION, AUDIOSTREAMS_PATCH_VERSION)

#cmakedefine01 USE_NETWORK_STACK
