///
/// \brief header file containing configuration values set during cmake build.
///
/// do not edit! this file is generated by cmake during the build process and any changes will be overwritten.
///

#pragma once

#define AUDIOSTREAMS_STRING_VERSION "@PROJECT_VERSION@"
#define AUDIOSTREAMS_MAJOR_VERSION @PROJECT_VERSION_MAJOR@
#define AUDIOSTREAMS_MINOR_VERSION @PROJECT_VERSION_MINOR@
#define AUDIOSTREAMS_PATCH_VERSION @PROJECT_VERSION_PATCH@
